import { Poppins } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";
import { ToastProvider } from "@/lib/ToastProvider";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
         <ToastProvider className='mt-5'/>
       <Navigation/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
