export const projectsData = [
  {
    id: 1,
    title: "React Portfolio Website",
    description:
      "TCMP is a platform that provides remote healthcare services. My team and I re-designed TCMP website and dashboard, we implemented new UI and features. We optimized the code and API to ensure an amazing user experience.",
    image: "/images/projects/1.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
    stacks: ["React", "Next.js", "Express", "MongoDB"],
  },
  {
    id: 2,
    title: "Potography Portfolio Website",
    description:
      "Website for The Saints Gathering Church with exciting features like downloadable sermons and devotionals. ",
    image: "/images/projects/3.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
    stacks: ["React", "Next.js", "Express", "MongoDB"],
  },
  {
    id: 3,
    title: "E-commerce Application",
    description: "Project 3 description",
    image: "/images/projects/3.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
    stacks: ["React", "Next.js", "Express", "MongoDB"],
  },
  {
    id: 4,
    title: "Food Ordering Application",
    description: "Project 4 description",
    image: "/images/projects/4.png",
    tag: ["All", "Mobile"],
    gitUrl: "/",
    previewUrl: "/",
    stacks: ["React", "Next.js", "Express", "MongoDB"],
  },
  {
    id: 5,
    title: "React Firebase Template",
    description: "Authentication and CRUD operations",
    image: "/images/projects/5.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
    stacks: ["React", "Next.js", "Express", "MongoDB"],
  },
  {
    id: 6,
    title: "Full-stack Roadmap",
    description: "Project 5 description",
    image: "/images/projects/6.png",
    tag: ["All", "Web"],
    gitUrl: "/",
    previewUrl: "/",
    stacks: ["React", "Next.js", "Express", "MongoDB"],
  },
];